### ISSUE TITLE
[PHP 8.0] Support Constructor Property Promotion

### ISSUE THREAD

**Issue by ruudk** [murtukov/php-code-generator#7]
Is this already supported? If not, it would be great to add it. 

https://stitcher.io/blog/constructor-promotion-in-php-8

**Comment by murtukov** [comment]
@ruudk It’s not supported yet, but will be added. Maybe even today.

**Comment by murtukov** [comment]
@ruudk 

Released the version **0.1.6** with support of Constructor Property Promotion

https://github.com/murtukov/php-code-generator#constructor-propertiy-promotion

**Comment by murtukov** [comment]
If you have any other feature requests, please feel free to open another issue.

**Comment by ruudk** [comment]
Thank you 🙌
